### ISSUE TITLE
JSONLogger bug in Basic Tour example 

### ISSUE THREAD

**Issue by darryl34** [bayesian-optimization/BayesianOptimization#438]
As seen in the example, we can save and load our progress with a logger file.
```py
logger = JSONLogger(path="./logs.log")
load_logs(new_optimizer, logs=["./logs.log"])
```

As the specified file does not have the .json extension, it will be appended to it as seen in logger.py line 138. 
```py
class JSONLogger(_Tracker):
    def __init__(self, path, reset=True):
        self._path = path if path[-5:] == ".json" else path + ".json"
```
However, this causes a FileNotFoundError as the file is now "logs.log.json" instead. Perhaps a fix would be to edit the notebook and a note saying that the given file will have the .json extension added to it if its not already one.

**Comment by till-m** [comment]
Hi @darryl34,

I suspect the problem here is a mismatch in versions. Recently (#420), we changed the logger to not force `.json` as extension, and updated the notebooks correspondingly. This was primarily done since the output was not actually valid `.json`. 
However, a version with this change not been released yet. I'm not sure what the current plan is with regard to releases. I suspect we could just make a release now, unfortunately I'm not too familiar with the process.

**Comment by darryl34** [comment]
Ah okay thats great to hear! Thanks!
