### ISSUE TITLE
How to specify pbounds when there are no variable names per se

### ISSUE THREAD

**Issue by tomsturges** [bayesian-optimization/BayesianOptimization#446]
How do I create `pbounds` when the function I am optimising can take in an arbitrary number of parameters, e.g. 

```
def bayes_opt_function(*p):
        return my_function(np.array(p))
```

Thanks

**Comment by till-m** [comment]
Hi @tomsturges, 

the number of parameters needs to be fixed. What kind of problem are you working with?

**Comment by tomsturges** [comment]
So I have some code for running an optics simulation. One of the optical components is a piece of glass with a topography (height profile) that can be arbitrary. I am parameterising this height profile with a polynomial. I have a config.yaml file which sets up the whole simulation. One of the parameters is the order of the polynomial I would like to consider. So what I end up optimising is the coefficients of a polynomial, which can vary depending on the config file. I would like to automate the whole process so that e.g. the order of the polynomial and the bounds can be specified in the config file and then the code sets up the optimisation and `pbounds`. Hence I'm trying to think of a way I can accomplish this. Thanks for your consideration.

**Comment by till-m** [comment]
First of all, there would be the straightforward way of doing it which is using a very high degree since an n-degree polynomial can be considered an (n+1)-degree polynomial with the (n+1)th coefficient being zero. Please note, that BO is not the best optimization to use for high dimensional optimization settings though.
However I think you might want to question the general idea behind what you're doing. BO relies on the euclidean distance of your data points being meaningful. I think this is not necessarily the case if what you're considering is a vector of polynomial coefficients. As a suggestion, I would look into parameterising your profile with a linear combination of [orthogonal polynomials](https://en.wikipedia.org/wiki/Classical_orthogonal_polynomials), e.g. [Chebyshev polynomials](https://en.wikipedia.org/wiki/Classical_orthogonal_polynomials#Chebyshev_polynomials) or use some other way of specifying the profile that does not use polynomials.

Disclaimer: This is a tricky problem, and I'm just listing ideas that come to mind.

**Comment by till-m** [comment]
From the technical/programming perspective, see #349.

**Comment by tomsturges** [comment]
Thanks very much for your suggestions. I will look into them and consider them in my project.

**Comment by Sulstice** [comment]
Ah! I was having the same problem and was about to implement the kwargs route. I have about 20,000 parameters and I didn't know exactly about how to do this.

**Comment by till-m** [comment]
@Sulstice if your problem is this high-dimensional you might want to look for a different optimization method. The rule-of-thumb for BO is a maximum dimension of 20, to get an accurate model of the system with this many parameters you'd have to sample points in the ten thousands and with GPR scaling cubically you will run into problems.
